---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaoxuefei.
--- DateTime: 2021/9/12 10:44 上午
---

function SwitchScene(sceneName)
    local r = CS.UnityEngine.Vector3.up * CS.UnityEngine.Time.deltaTime
    prefab.transform:Rotate(r)
end